### ISSUE TITLE
Cannot build back :)

### ISSUE THREAD

**Issue by ymeunier** [amundi/onSiteManagement#2]
Hi,
Can you suppress this line in pom.xml back's :
` <generateGitPropertiesFile>true</generateGitPropertiesFile>`

Or add this line
` <failOnNoGitDirectory>false</failOnNoGitDirectory>`

Best regards,
Yann

**Comment by FabriceGazin** [comment]
I added `<failOnNoGitDirectory>false</failOnNoGitDirectory>` :)
